/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWeatherRouteImport } from './routes/_app.weather'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppFarmsRouteImport } from './routes/_app.farms'
import { Route as AppDiagnosticsRouteImport } from './routes/_app.diagnostics'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppChatbotRouteImport } from './routes/_app.chatbot'
import { Route as AppBlogsRouteImport } from './routes/_app.blogs'
import { Route as AppProfileIndexRouteImport } from './routes/_app.profile.index'
import { Route as AppFarmsIndexRouteImport } from './routes/_app.farms.index'
import { Route as AppChatsIndexRouteImport } from './routes/_app.chats.index'
import { Route as AppProfileUserIdRouteImport } from './routes/_app.profile.$userId'
import { Route as AppFarmsFarmIdRouteImport } from './routes/_app.farms.$farmId'
import { Route as AppChatsChatIdRouteImport } from './routes/_app.chats.$chatId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeatherRoute = AppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmsRoute = AppFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticsRoute = AppDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogsRoute = AppBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppFarmsIndexRoute = AppFarmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFarmsRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatsRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppFarmsFarmIdRoute = AppFarmsFarmIdRouteImport.update({
  id: '/$farmId',
  path: '/$farmId',
  getParentRoute: () => AppFarmsRoute,
} as any)
const AppChatsChatIdRoute = AppChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AppChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blogs': typeof AppBlogsRoute
  '/chatbot': typeof AppChatbotRoute
  '/chats': typeof AppChatsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/diagnostics': typeof AppDiagnosticsRoute
  '/farms': typeof AppFarmsRouteWithChildren
  '/profile': typeof AppProfileRouteWithChildren
  '/weather': typeof AppWeatherRoute
  '/chats/$chatId': typeof AppChatsChatIdRoute
  '/farms/$farmId': typeof AppFarmsFarmIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/chats/': typeof AppChatsIndexRoute
  '/farms/': typeof AppFarmsIndexRoute
  '/profile/': typeof AppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blogs': typeof AppBlogsRoute
  '/chatbot': typeof AppChatbotRoute
  '/dashboard': typeof AppDashboardRoute
  '/diagnostics': typeof AppDiagnosticsRoute
  '/weather': typeof AppWeatherRoute
  '/chats/$chatId': typeof AppChatsChatIdRoute
  '/farms/$farmId': typeof AppFarmsFarmIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/chats': typeof AppChatsIndexRoute
  '/farms': typeof AppFarmsIndexRoute
  '/profile': typeof AppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/blogs': typeof AppBlogsRoute
  '/_app/chatbot': typeof AppChatbotRoute
  '/_app/chats': typeof AppChatsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diagnostics': typeof AppDiagnosticsRoute
  '/_app/farms': typeof AppFarmsRouteWithChildren
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/weather': typeof AppWeatherRoute
  '/_app/chats/$chatId': typeof AppChatsChatIdRoute
  '/_app/farms/$farmId': typeof AppFarmsFarmIdRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
  '/_app/chats/': typeof AppChatsIndexRoute
  '/_app/farms/': typeof AppFarmsIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/blogs'
    | '/chatbot'
    | '/chats'
    | '/dashboard'
    | '/diagnostics'
    | '/farms'
    | '/profile'
    | '/weather'
    | '/chats/$chatId'
    | '/farms/$farmId'
    | '/profile/$userId'
    | '/chats/'
    | '/farms/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/blogs'
    | '/chatbot'
    | '/dashboard'
    | '/diagnostics'
    | '/weather'
    | '/chats/$chatId'
    | '/farms/$farmId'
    | '/profile/$userId'
    | '/chats'
    | '/farms'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_app/blogs'
    | '/_app/chatbot'
    | '/_app/chats'
    | '/_app/dashboard'
    | '/_app/diagnostics'
    | '/_app/farms'
    | '/_app/profile'
    | '/_app/weather'
    | '/_app/chats/$chatId'
    | '/_app/farms/$farmId'
    | '/_app/profile/$userId'
    | '/_app/chats/'
    | '/_app/farms/'
    | '/_app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weather': {
      id: '/_app/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AppWeatherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farms': {
      id: '/_app/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof AppFarmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnostics': {
      id: '/_app/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AppDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chatbot': {
      id: '/_app/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blogs': {
      id: '/_app/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof AppBlogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/farms/': {
      id: '/_app/farms/'
      path: '/'
      fullPath: '/farms/'
      preLoaderRoute: typeof AppFarmsIndexRouteImport
      parentRoute: typeof AppFarmsRoute
    }
    '/_app/chats/': {
      id: '/_app/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppChatsRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/farms/$farmId': {
      id: '/_app/farms/$farmId'
      path: '/$farmId'
      fullPath: '/farms/$farmId'
      preLoaderRoute: typeof AppFarmsFarmIdRouteImport
      parentRoute: typeof AppFarmsRoute
    }
    '/_app/chats/$chatId': {
      id: '/_app/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AppChatsChatIdRouteImport
      parentRoute: typeof AppChatsRoute
    }
  }
}

interface AppChatsRouteChildren {
  AppChatsChatIdRoute: typeof AppChatsChatIdRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
}

const AppChatsRouteChildren: AppChatsRouteChildren = {
  AppChatsChatIdRoute: AppChatsChatIdRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
}

const AppChatsRouteWithChildren = AppChatsRoute._addFileChildren(
  AppChatsRouteChildren,
)

interface AppFarmsRouteChildren {
  AppFarmsFarmIdRoute: typeof AppFarmsFarmIdRoute
  AppFarmsIndexRoute: typeof AppFarmsIndexRoute
}

const AppFarmsRouteChildren: AppFarmsRouteChildren = {
  AppFarmsFarmIdRoute: AppFarmsFarmIdRoute,
  AppFarmsIndexRoute: AppFarmsIndexRoute,
}

const AppFarmsRouteWithChildren = AppFarmsRoute._addFileChildren(
  AppFarmsRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUserIdRoute: AppProfileUserIdRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppBlogsRoute: typeof AppBlogsRoute
  AppChatbotRoute: typeof AppChatbotRoute
  AppChatsRoute: typeof AppChatsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiagnosticsRoute: typeof AppDiagnosticsRoute
  AppFarmsRoute: typeof AppFarmsRouteWithChildren
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppWeatherRoute: typeof AppWeatherRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBlogsRoute: AppBlogsRoute,
  AppChatbotRoute: AppChatbotRoute,
  AppChatsRoute: AppChatsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDiagnosticsRoute: AppDiagnosticsRoute,
  AppFarmsRoute: AppFarmsRouteWithChildren,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppWeatherRoute: AppWeatherRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
